services:
  redmine-db:
    image: postgres:16
    environment:
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: redmine
      POSTGRES_DB: redmine
    volumes:
      - redmine-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  redmine:
    image: redmine:6.0.6-bookworm
    depends_on: [redmine-db]
    environment:
      REDMINE_DB_POSTGRES: redmine-db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_SECRET_KEY_BASE: changeme
    ports:
      - "3000:3000"           # http://localhost:3000
    volumes:
      - redmine-files:/usr/src/redmine/files
      - redmine-plugins:/usr/src/redmine/plugins
      - redmine-themes:/usr/src/redmine/public/themes
    restart: unless-stopped

  gitlab:
    image: gitlab/gitlab-ce:18.3.0-ce.0
    hostname: gitlab.local
    environment:
      GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PASSWORD}
      GITLAB_ROOT_EMAIL: ${GITLAB_ROOT_EMAIL}
      TZ: ${TZ}
    shm_size: "1g"
    ports:
      - "8888:80"             # http://localhost:8080
      - "2222:22"             # SSH
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    restart: unless-stopped

  bridge:
    build:
      context: ./bridge
    environment:
      # Filled via .env (see .env.example)
      REDMINE_URL: ${REDMINE_URL}
      REDMINE_API_KEY: ${REDMINE_API_KEY}
      REDMINE_WEBHOOK_SECRET: ${REDMINE_WEBHOOK_SECRET}
      GITLAB_URL: ${GITLAB_URL}
      GITLAB_TOKEN: ${GITLAB_TOKEN}
      GITLAB_WEBHOOK_SECRET: ${GITLAB_WEBHOOK_SECRET}
      MIRROR_STRATEGY: ${MIRROR_STRATEGY}
      MAPPING_PATH: /app/mapping.json
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      - ./bridge/mapping.example.json:/app/mapping.json:ro
    ports:
      - "5001:5001"           # http://localhost:5001/health
    depends_on: [redmine, gitlab]
    restart: unless-stopped

volumes:
  redmine-db-data: {}
  redmine-files: {}
  redmine-plugins: {}
  redmine-themes: {}
  gitlab-config: {}
  gitlab-logs: {}
  gitlab-data: {}
