// <auto-generated />
using System;
using Bridge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bridge.Migrations
{
    [DbContext(typeof(SyncDbContext))]
    [Migration("20250924154158_addstatusestable23")]
    partial class addstatusestable23
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Bridge.Data.GitLabProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("GitLabProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathWithNamespace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectSyncId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectSyncId")
                        .IsUnique();

                    b.ToTable("GitLabProjects");
                });

            modelBuilder.Entity("Bridge.Data.IssueMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalSnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("GitLabIssueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastGitLabEventUuid")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectSyncId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedmineIssueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GitLabIssueId")
                        .IsUnique();

                    b.HasIndex("ProjectSyncId");

                    b.HasIndex("RedmineIssueId")
                        .IsUnique();

                    b.ToTable("IssueMappings");
                });

            modelBuilder.Entity("Bridge.Data.ProjectSync", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSyncUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedmineIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RedmineProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RedmineProjectId")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Bridge.Data.StatusRedmine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RedmineStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RedmineStatusId")
                        .IsUnique();

                    b.ToTable("StatusesRedmine");
                });

            modelBuilder.Entity("Bridge.Data.TrackerRedmine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RedmineTrackerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RedmineTrackerId")
                        .IsUnique();

                    b.ToTable("TrackersRedmine");
                });

            modelBuilder.Entity("Bridge.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GitLabUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RedmineUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GitLabUserId")
                        .IsUnique();

                    b.HasIndex("RedmineUserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bridge.Data.GitLabProject", b =>
                {
                    b.HasOne("Bridge.Data.ProjectSync", "ProjectSync")
                        .WithOne("GitLabProject")
                        .HasForeignKey("Bridge.Data.GitLabProject", "ProjectSyncId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectSync");
                });

            modelBuilder.Entity("Bridge.Data.IssueMapping", b =>
                {
                    b.HasOne("Bridge.Data.ProjectSync", "ProjectSync")
                        .WithMany()
                        .HasForeignKey("ProjectSyncId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectSync");
                });

            modelBuilder.Entity("Bridge.Data.ProjectSync", b =>
                {
                    b.Navigation("GitLabProject");
                });
#pragma warning restore 612, 618
        }
    }
}
